######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 17 17:57:50 2013
######################################################################

QT += gui core

TEMPLATE = app

TARGET = toroidal-clock5


# Input
HEADERS += ToroidalClock5.h

SOURCES +=	main.cpp\
			ToroidalClock5.cpp

OTHER_FILES = \
			LICENSE\
			README.md
